GET http://localhost:3001/task-management

###
POST http://localhost:3001/newTask
Content-Type: application/json

{
"task": "brainstorming session",
"description": "live session with Trench housing",
"dueDate": "Monday",
"status": "done"
}

###
GET http://localhost:3001/newTask/e786a6a4-2898-44d9-80bb-f8dc0512b686
 
###
PUT http://localhost:3001/newTask/e786a6a4-2898-44d9-80bb-f8dc0512b686
Content-Type: application/json

{
"task": "Interview",
"description": "Interview session with Fiiwe barry",
"dueDate": "Thursday",
"status": "pending"
}
###
PATCH http://localhost:3000/newTask/e786a6a4-2898-44d9-80bb-f8dc0512b686
Content-Type: application/json

{
"task": "ve Coding", 
"description": "live coding session", 
"status": "Pending",
"dueDate":"saturday"
}

###
DELETE http://localhost:3001/newTask/e786a6a4-2898-44d9-80bb-f8dc0512b686
